# Generated by Django 5.1.1 on 2024-09-30 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="question",
        ),
    ]
