# Generated by Django 5.1.1 on 2024-09-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_remove_quiz_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="question",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
